export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  GIT_ERROR = 'GIT_ERROR',
  PROXY_ERROR = 'PROXY_ERROR',
  OAUTH_ERROR = 'OAUTH_ERROR',
}
